### ISSUE TITLE
Escaping from full size video watching resizes parent web browser window

### ISSUE THREAD

**Issue by jbatteen** [bbidulock/icewm#538] opened 2021-01-09 17:41 UTC
With the latest update, in both chromium and Firefox, escaping from full screen video such as YouTube resizes the parent web browser window where it was maximized before.  I am using triple monitors, unsure if this is relevant.  Version 2.0.0 on OpenBSD.

As an aside, thank you for adopting icewm and providing new updates!!  I wish I weren't on a student budget and unable to donate.  Give me two more years.

**Comment by jbatteen** [comment] 2021-01-09 17:47
![image](https://user-images.githubusercontent.com/77206227/104104870-3f7e7900-5270-11eb-8385-50cb49d370cf.png)

![image](https://user-images.githubusercontent.com/77206227/104104873-45745a00-5270-11eb-87a1-4d73bdb37e39.png)

![image](https://user-images.githubusercontent.com/77206227/104104881-4c02d180-5270-11eb-9faf-a3a0d9f1e10f.png)

littleguy$ xrandr                                                                                                                                                                              
Screen 0: minimum 320 x 200, current 4566 x 1080, maximum 16384 x 16384                                                                                                                        
eDP-1 connected primary 1366x768+0+312 (normal left inverted right x axis y axis) 344mm x 193mm                                                                                                
   1366x768      60.06*+                                                                                                                                                                       
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   640x400       59.88    59.98  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)
DP-2-1 disconnected (normal left inverted right x axis y axis)
DP-2-2 connected 1920x1080+1366+0 (normal left inverted right x axis y axis) 598
   1920x1080     60.00*+
   1680x1050     59.88  
   1280x1024     75.02    60.02  
   1440x900      74.98    59.90  
   1280x960      60.00  
   1152x864      75.00  
   1280x720      60.00  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    66.67    59.94  
   720x400       70.08  
DP-2-3 connected 1280x1024+3286+56 (normal left inverted right x axis y axis) 37
   1280x1024     60.02*+  75.02  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    66.67    59.94  
   720x400       70.08

**Comment by gijsbers** [comment] 2021-01-09 19:50
Is this a duplicate of issue #533?

**Comment by jbatteen** [comment] 2021-01-09 20:22
Yes it appears so.  I can duplicate it with any other window by going Alt-F10 to maximize, Alt-F11 to fullscreen, and the next Alt-F11 brings me back to the non-maximized window geometry.  However, this is most certainly not desired behavior.  No other window manager behaves as the new update does.  "Additionally the Window Manager is responsible for restoring the original geometry after a switch from fullscreen back to normal window."  This means that the window manager should restore the window to whatever geometry it had before going fullscreen, whether that geometry was maximized or otherwise.

**Comment by jbatteen** [comment] 2021-01-09 21:10
Here is what happens if I use Alt-F10 to return to a maximized state as described in #553, rather than hitting escape as usual.  It requires a further escape to return to a standard maximized state.

Normal video viewing:
![image](https://user-images.githubusercontent.com/77206227/104108735-a3af3600-528c-11eb-8abc-a256d087164e.png)

After pressing f for fullscreen:
![image](https://user-images.githubusercontent.com/77206227/104108739-ad389e00-528c-11eb-8d1b-147917d5e182.png)

After Alt-F10 to return to maximized state:
![image](https://user-images.githubusercontent.com/77206227/104108745-bb86ba00-528c-11eb-89b7-6f09de31cf6e.png)

After escape to return to intended maximized state:
![image](https://user-images.githubusercontent.com/77206227/104108751-c9d4d600-528c-11eb-80a1-c86b6ea71a96.png)

**Comment by gijsbers** [comment] 2021-01-12 20:08
What browser + version + distro is that?

**Comment by jbatteen** [comment] 2021-01-13 02:20
It happens with both firefox-84.0.2 and chromium-87.0.4280.141 on OpenBSD 6.8-current

**Comment by gijsbers** [comment] 2021-01-20 00:54
Thanks! Please test.

**Comment by jbatteen** [comment] 2021-01-23 17:27
It works!  Thanks!!

**Comment by Code7R** [comment] 2021-02-06 13:46
Hi, I see a side effect which might be related. Repro:

- use a recent Firefox
- Open YouTube
- Set window maximized
- Send Video to fullscreen mode (double-click the video)
- Result: Video is maximized but the Window remains in maximized non-fullscreen mode

Do the same without setting the window maximized before and fullscreen works as expected, the decorations are removed. Interestingly, I cannot reproduce this with Chromium.

Edit: it does also not happen on the primary screen (where the taskbar is located), only on the second screen.

**Comment by gijsbers** [comment] 2021-02-06 15:14
It's not so clear what is causing this: FF or Ice. Ideally you give some trace with logevents and/or `icesh spy`.

**Comment by jbatteen** [comment] 2021-02-06 19:36
I cannot replicate with Firefox 85.0, IceWM 2.1.1, OpenBSD 6.8-current

**Closed as completed** 2022-11-09 19:59 UTC
Labels: closure-requested
