### ISSUE TITLE
Wrong icon in alt+tab dialog

### ISSUE THREAD

**Issue by covex** [bbidulock/icewm#396] opened 2019-11-11 11:46 UTC
I am out of ideas, and not sure how to describe this. This is fedora 30, latest git icewm. Just opening xterm with bash and pressing the enter causes some window properties to change and the window title to disappear, pressing again the title returns. From `xprop` I found this:

    [covex@me ~]$ xprop | grep NAME
    WM_LOCALE_NAME(STRING) = "en_US.utf8"
    WM_ICON_NAME(STRING) = "covex@me:~"
    WM_NAME(STRING) = "covex@me:~"
    [covex@me ~]$ xprop | grep NAME
    _NET_WM_VISIBLE_NAME(UTF8_STRING) = "covex@me:~"
    _NET_WM_VISIBLE_ICON_NAME(UTF8_STRING) = "covex@me:~"
    _NET_WM_NAME(UTF8_STRING) = "covex@me:~"
    _NET_WM_ICON_NAME(UTF8_STRING) = "covex@me:~"
    WM_LOCALE_NAME(STRING) = "en_US.utf8"
    WM_ICON_NAME(STRING) = "covex@me:~"
    WM_NAME(STRING) = "covex@me:~"

Also while the icon of xterm is corretly take from ~/.icewm/icons for a taskbar and window frame, the alt+tab dialog shows a completely different one (not sure where it comes from). icewm-.1.3.8 (I know very old but from the fedora repo) is OK.

**Comment by covex** [comment] 2019-11-11 12:31
OK I found the icon for the alt+tab is comming from /usr/share/pixmaps/xterm_32x32.xpm.. not sure why this window is using a different icon source as default icewm icon is the same as the one I have in ~/.icewm/icons.

**Comment by bbidulock** [comment] 2019-11-11 13:28
Sounds like the same thing as #395

**Comment by covex** [comment] 2019-11-11 18:48
Yes the disapearing title seems the same.

How about the icons in alt+tab window?

**Comment by covex** [comment] 2019-11-14 08:57
Fedora 30 update (testing) https://koji.fedoraproject.org/koji/buildinfo?buildID=1412763 fixes xterm title for me.

**Comment by gijsbers** [comment] 2019-11-16 21:20
@covex As the issue was a duplicate and not related to icewm and fixed now, is this issue closable?

**Comment by covex** [comment] 2019-11-17 12:56
Should I create a new issue for the icon in the Alt+Tab switch (I first though it could be related but probably not.). See second comment.

**Comment by gijsbers** [comment] 2019-11-17 13:33
Good you point that out. If that problem still applies to the current git repository code then you could simply remove the irrelevant part from the title and keep only what you hope to be improved. Please check that it applies to the current code and summarize a reproducing scenario for us in steps.

**Comment by covex** [comment] 2019-11-17 18:29
The icon in taskbar is taken correctly either from ~/.icewm/icons/xterm_32x32.xpm or icewm install directory (defined thru winoptions), but for some reason the icon in the Alt+Tab window is taken from /usr/share/pixmaps/xterm_32x32.xpm
See picture [http://www.lowlevel.cz/log/images/icewm-xterm.png](http://www.lowlevel.cz/log/images/icewm-xterm.png)
Maybe it applies also for other apps, but this one is obvious. This is for latest git clone and was not happening in older icewm versions like 1.3.8.

**Comment by gijsbers** [comment] 2019-11-17 20:13
Could you examine if it has something to do with the availability of different icon sizes?
The Alt+Tab searches for larger icons than the taskbar or menu.

**Comment by covex** [comment] 2019-11-21 07:23
Hm, this could be icewm only distributes the 16x16 and 32x32, while the system has 48x48:
/home/covex/.icewm/icons/xterm_16x16.xpm
/home/covex/.icewm/icons/xterm_32x32.xpm
/usr/share/icewm/icons/xterm_16x16.xpm
/usr/share/icewm/icons/xterm_32x32.xpm
/usr/share/pixmaps/xterm_32x32.xpm
/usr/share/pixmaps/xterm_48x48.xpm
but to me it seems the 32x32 is used for alt+tab and I tried to create a 48x48 version in ~/.icewm/icons but it did not change anything. Note the home and icewm pixmaxps are the same in this case, just the /usr/share/pixmaps/xterm* is that comming from xterm package.

**Comment by gijsbers** [comment] 2019-11-22 22:19
Good! Could you use commit b9544467f to see which xpm is loaded by --trace=icon?

**Comment by covex** [comment] 2019-11-24 14:22
I may need some instructions how to use it properly, I thought 
icewm --replace --trace=icon would work, but this crashes a complete icewm session.
Using just xinit and starting the icewm --trace on "empty" account there is this
$ icewm --trace=icon
15:15:55.056: IceWM: icon open: /usr/share/icewm/icons/xterm_16x16.xpm
15:15:55.144: IceWM: icon open: /usr/share/icons/oxygen/base/16x16/apps/utilities-terminal.png
15:15:58.601: IceWM: icon open: /usr/share/pixmaps/xterm_32x32.xpm
but the 32x32.xpm is also present in /usr/share/icewm/icons

It seems to me like the /usr/share/pixmaps has the preference over icewm/icons and also ~/.icewm/icons.

**Comment by gijsbers** [comment] 2019-11-24 14:26
You can examine your IconPath by:

    icewm --postpreferences | grep IconPath

**Comment by gijsbers** [comment] 2019-11-24 14:27
For testing run a `Xephyr` and then `icewm -d :1` ......

**Comment by gijsbers** [comment] 2019-11-24 14:33
You could also define a prefix path for icons in winoptions like:

    xterm.XTerm.icon: /usr/share/pixmaps/xterm-color

Then icewm will try to complete that by adding sizes and suffixes.

**Comment by covex** [comment] 2019-11-24 15:59
To not missunderstand - I want Icewm to use icons from icewm.

$ icewm --postpreferences | grep IconPath
IconPath="/usr/share/icons/oxygen/base:/usr/share/icons/Adwaita:/usr/share/icons/hicolor:/usr/share/icons:/usr/share/pixmaps:/usr/local/share/icons/hicolor:"

Not sure where those paths come from, but I do not have IconPath specified in my preferences file, so this is some kind of default. Icewm icon path is not in there thou... so the icons from icewm are some kind of fallback then?

Using winoption
xterm.icon: /usr/share/icewm/icons/xterm
I may "fix" that for this particular case. But this path preference order seem weired, I would expect icewm to prefere icewm icons, but I know there were always troubles with order of preferences and for that reason the "prefoverride" was introduced.

**Comment by gijsbers** [comment] 2019-11-24 16:23
IceWM first looks at `IconPath` and then at the ICEWM_PRIVCFG (or $HOME/.icewm), then at theme icons, then at CFGDIR/icons, then at LIBDIR/icons. What "seems weird" is subjective.
I don't claim that this is the best. It has some merits. Users can override it easily by defining IconPath. Since icewm icons are old, they lack the sophistication of modern system icons.
Open for discussion.

**Comment by covex** [comment] 2019-11-24 17:08
No problem with that, just it is a change from older versions. It would be nice if the https://github.com/ice-wm/FAQ/blob/master/index.md#how-to-add-icons could be improved to state exactly what you wrote now about paths. Thanks a lot

**Comment by Code7R** [comment] 2019-11-29 11:40
By the way, can --trace be documented please? Thank you.

> $ build-test/icewm -h | grep trace
> $

**Closed as completed** 2022-12-03 12:31 UTC
