### ISSUE TITLE
Always 1px black window border on right and bottom

### ISSUE THREAD

**Issue by fladd** [bbidulock/icewm#784] opened 2024-08-29 20:20 UTC
It seems that all windows have a hardcoded black border at the right and bottom, when BorderSizeX and BoderSizeY are >= 1.

Using the "flat" look, I have both border sizes set to 1, and changing ColorNormalBorder or ColorActiveBorder will only affect the top and left borders (the resulting colour is actually also not exactly the one I specify, but a bit brighter one).

I don't seem to be able to set a 1 px border of the same colour around the entire window.

This issue also affects the QuickSwitch window, which, using the "flat" look, always shows this 1 px black border on the right and bottom, while not showing any border at all on the top and left.

Again, here I don't seem to be able to set a border of the same color around the entire window.

**Comment by gijsbers** [comment] 2024-09-10 21:20
Duplicate of ice-wm/icewm#174.

**Closed as not planned by gijsbers** 2024-09-10 21:20 UTC
Labels: duplicate
