### ISSUE TITLE
Be sure the user can see the bottom borders of windows that indeed don't go past the bottom of the screen

### ISSUE THREAD

**Issue by jidanni** [bbidulock/icewm#556] opened 2021-02-24 18:40 UTC
1. Install Google Chrome, e.g., 90.0.4421.5 (Official Build) dev (64-bit) 
```
# cat /etc/apt/sources.list.d/google-chrome-unstable.list 
deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
```
2. Open it and browse a new tab.

Here's what the bottom of the screen looks like:
![20210225T021606](https://user-images.githubusercontent.com/1230959/109047867-576f6680-7711-11eb-8b9f-aff010f3f6a5.jpg)

The problem is it very much appears the browser extends off the bottom of the screen! One inch? One mile? Who knows.

OK, now using ALT+Hold Left Mouse Button I have moved it up to have a better look:
![20210225T023123](https://user-images.githubusercontent.com/1230959/109048214-c9e04680-7711-11eb-877b-6ee3789d2122.jpg)

So fortunately my fears were unfounded. The only thing that was wrong in our first image was **the thin grey line that composes the bottom border of the chrome window extends off the bottom of the screen!** (Extends below the tab bar.)

Therefore icewm should make sure the user can always see it. No big "skin off icewm's back." Just a millimeter or so.

One could say "Well use ALT+Hold Left Mouse Button and do it yourself". Alas once I move it too low, it snaps into place. I.e., there is no way to even make it get lower than my second image, without snapping into place as shown in my first image!

**Comment by zaza42** [comment] 2021-02-25 08:44
Duplicate of https://github.com/bbidulock/icewm/issues/550 ?

**Comment by jidanni** [comment] 2021-02-26 01:59
> Duplicate of #550 ?

Not sure. I apparently use a [2012 version](285).
```
$ icewm --version
IceWM 2.1.2, Copyright 1997-2012 Marko Macek, 2001 Mathias Hasselmann.
```

**Closed as completed** 2021-02-28 23:40 UTC
Labels: duplicate
