### ISSUE TITLE
runonce-programs on other workspace

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/icewm#301] opened 2018-09-22 08:26 UTC
If the runonce-program or libreoffice/evince with the open file are on other workspace, then in attempt to start the program (to open the same file in libreoffice/evince) leads to what icewm switches to other workspace

If libreoffice is maximized, then is not clear that occurred.
I want to look at "Process Status" and all windows vanish :)

It seems to me on the contrary, the window shall move on workspace (or this behavior shall be configured).

**Comment by gijsbers** [comment] 2018-09-22 14:50
If you want that then you could use a tool like `wmctrl` to move the app to your current workspace.

**Comment by arsonoff** [comment] 2018-09-22 16:50
I open on Workspace1 the file1.ods in libreoffice. 
I switch to Workspace2, I open five programs, I work 4 hours.
I start libreoffice, I open file1.ods, opened... Alt+Tab, where all programs?!

In my opinion it is natural that when I start the program, I want that it appeared in my existing environment, but not I moved to the program (if suddenly it is open on other workspace)

**Comment by gijsbers** [comment] 2018-09-22 17:12
Works fine here. Maybe there is some setting in libreoffice?
Or you can set Occupy All.
Alt+Tab by default only lists current workspace,
but you can change this by QuickSwitchToAllWorkspaces.
Or you can use the window list.
So many fine ways to adapt things to your wishes...
Or to adapt your wishes to the way things are...
Enjoy! :-)

**Comment by arsonoff** [comment] 2018-09-22 18:13
It was the example and settings of Alt+Tab will not help, as well as settings libreoffice.

How setup of Alt+Tab will help if I want to see one document near another for comparison?

Click "Process status" taskbar, switch to other workspace, start couple of programs and look what of programs loads the processor stronger :)

I have reference books (pdf, ods) in which I constantly look and I compare. I shall hold in the head all the time they are open or are closed and on what workspace. And to make the set of gestures on their movement.

It is necessary only that not I went to the window, but it to me :)

**Comment by gijsbers** [comment] 2018-09-22 18:19
> It is necessary only that not I went to the window, but it to me :)

Well you know how to define keyboard shortcuts to scripts.
Then you can do `wmctrl -l`, grep what you want and move it to your current desktop with:

       wmctrl -R <WIN>
              Move  the window <WIN> to the current desktop, raise the window, and
              give it focus.

**Comment by arsonoff** [comment] 2018-09-22 18:47
I apologize for my very bad english (it is computer translation),
but we do not understand each other.

I do not know as it is possible to apply this command to dialog of opening of the file of application (libreoffice/evince/etc.).

**Comment by arsonoff** [comment] 2018-09-26 14:32
The behavior IceWM is not predictable, in the sense that when opening files in the application (libreoffice, evince) or start of "Network/Process Status" (the being runonce-programs at default settings) you cannot predict (based on the data seen on the screen) on what workspace you appear after that. Can be on it, and can on another where before this application with this file was opened.

I cannot think up any scenario of work where such behavior is necessary.
But in real work it very much disturbs.

Workspace - space for work.:)
On one workspace files for one work, on another for another.
Until I finished work to me there is no wish to turn out on other workspace at all, only that I forgot to close on it the "Process Status" window.
In my opinion it will be logical if the window moves to the current workspace [: enhancement:]

P.S. The question not in how to move between workspaces or to move windows between them. The question is in what shall do IceWM when the person tries to open already open file or to start already started runonce-program.

**Comment by gijsbers** [comment] 2018-09-29 16:40
What are your focus settings? Run `icewm --postpreferences | grep -e Focus`

**Comment by arsonoff** [comment] 2018-10-05 17:39
```
ClickToFocus=1
FocusOnAppRaise=0
RequestFocusOnAppRaise=1
RaiseOnFocus=1
FocusOnClickClient=1
FocusChangesWorkspace=0
FocusOnMap=1
FocusOnMapTransient=0
FocusOnMapTransientActive=1
StrongPointerFocus=0
DelayPointerFocus=1
ShowFocusModeMenu=1
PointerFocusDelay=200
FocusRequestFlashTime=0
FocusRequestFlashInterval=250
```

**Comment by gijsbers** [comment] 2018-10-08 19:21
Why do you have `FocusChangesWorkspace=0`? You want the opposite.

**Comment by arsonoff** [comment] 2018-10-09 16:12
> Why do you have FocusChangesWorkspace=0? You want the opposite.

?!
I want that Focus did not change to me Workspace, but the window moved to me to Workspace.

And this the first that I tried to make. But change of this option did not affect this behavior in any way.
I did not even understand what this option influences as could not appropriate "Focus" to the window on other "Workspace".
Tried so:
```
workspace_1$ icewmhint xclock workspace 1 && xclock & # start xclock in workspace_2

workspace_1$ xdotool search --desktop 1 xclock 
Defaulting to search window name, class, and classname
25165834

workspace_1$ xdotool search --desktop 1 xclock windowfocus
Defaulting to search window name, class, and classname
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  42 (X_SetInputFocus)
  Serial number of failed request:  2741
  Current serial number in output stream:  2743
```
Start of the program on other Workspace did not transfer it Focus. 
xdotool gave the error message.

**Comment by arsonoff** [comment] 2018-10-09 16:19
Couple of refining:

1. Under runonce-program I meant programs the started by the directive runonce from menu/toolbar or standard programs from the tray ("Process Status", etc.)

There are still programs in settings of which there is the "only one instance" option (for example: smplayer, xnviewmp). They behave on another, but too it is not better. In attempt of the second start on other workspace there is in general no switching, the window appears only on taskbar (blinks) and only when clicking, jumps on other workspace.

2. Under start libreoffice I meant start Calc/Writer (`libreoffice --calc|--writer`), or opening of the file from FM.

Start libreoffice without parameters behaves in general not adequately, but it is not the problem icewm and any options probably will not correct it. 
Instead of opening of StartCenter libreoffice switches to any existing window on any workspace (as a rule this last open window with the application libreoffice, but not always)

**Comment by arsonoff** [comment] 2018-10-09 20:52
Perhaps we do not understand each other because we have different behavior of the program?
test (IceWM 1.4.2.1597, default settings, CentOS7.5):
- on workspace_1 start "Process Status" from the tray.
- switch to workspace_2 and again try to start "Process Status" from the tray.
- result: icewm switches to workspace_1
Switching of the option FocusChangesWorkspace of test result does not change.
So?

**Comment by gijsbers** [comment] 2018-10-13 08:39
@arsonoff Should work now.

**Comment by arsonoff** [comment] 2018-10-14 20:49
>always open applet command windows on current workspace

1. Applets do not receive focus:
 - On workspace_1 start "Process Status" and "Network status"
 - Pass to workspace_2, start the application (libreoffice, gimp, etc.)
 - Start "Process Status" and "Network status"
 - Windows of applets appear, but do not receive Focus

2. It not correctly works if instead of xterm to use urxvtd/urxvtc. My settings:

preferences:
```
...
CPUStatusCommand="urxvtc -name top -title Process\ Status -e top -d 1 -o %CPU"
CPUStatusClassHint="top.URxvt"
NetStatusCommand="urxvtc -name netstat -title 'Network Status' -e watch -n 1 ss -putan 'not src 127.0.0.1'"
NetStatusClassHint="netstat.URxvt"
...
```

.xinitrc:
```
...
urxvtd -q -f -o
exec icewm-session
```
- On workspace_1 start urxvtc, "Process Status" and "Network status":
```
$ wmctrl -lx
0x00400009  1 urxvt.URxvt           localhost.localdomain urxvt
0x00400016  1 netstat.URxvt         localhost.localdomain Network Status
0x00400023  1 top.URxvt             localhost.localdomain Process Status
```
- Pass to workspace_2
- Start "Process Status" three times 
- All three windows with workspace_1 move to workspace_2

**Comment by arsonoff** [comment] 2018-10-14 21:48
> FocusCurrentWorkspace moves newly focused windows to current workspace

1. There was the problem with the applications having own options "only one instance" (smplayer, xnviewmp, etc.).
In attempt of the second start on other workspace there is in general no switching, the window appears only on taskbar (blinks) and only when clicking, appears the window.

2. I consider that the action given options is too global.
It influences not only opening of files and start of programs, but also at choice in "window list" and quickswitch. 
But if in the first case I want to open the window (repeatedly), then in the second case is realized I want to switch.


3. What is done after all by the option `FocusChangesWorkspace`? I cannot understand what it influences.

**Comment by gijsbers** [comment] 2018-10-15 06:49
@arsonoff 
Applets 2 done, maybe 1. 
FocusCurrentWorkspace 2 done.
3 FocusChangesWorkspace is unclear, ignore for now.

**Comment by gijsbers** [comment] 2018-10-22 20:59
@arsonoff Can this be closed?

**Comment by arsonoff** [comment] 2018-10-23 05:09
> Applets do not receive focus:

The problem with Focus remained. The problem is shown only if on the current workspace the application is started (librteoffice, gimp) and only upon transition of "Process/network status" from other workspace. It is similar that the window at first receives Focus, and then loses it (in focus there is application).

> I consider that the action given options is too global.

QuickSwitch - OK (does not depend on the option FocusCurrentWorkspace), but "Window List" (Ctrl+Alt+Esc) and TaskBar (at TaskBarShowAllWindows=1) remained are dependent on the option.


There was the problem with smplayer/xnviewmp (see above). The problem is shown (on the miscellaneous) at any FocusCurrentWorkspace value.

**Comment by gijsbers** [comment] 2018-10-23 18:00
> Applets do not receive focus:

Cannot reproduce this. Can you make a screencast/video? Works fine here.

> I consider that the action given options is too global.

This is fixed now. Please try again.

> There was the problem with smplayer/xnviewmp.

Cannot reproduce this. Works fine here. What do you do wrong? ;-)

**Comment by gijsbers** [comment] 2018-10-23 18:05
I have:
`runonce smplayer smplayer "smplayer" /usr/bin/smplayer`

**Comment by arsonoff** [comment] 2018-10-23 19:48
> runonce smplayer smplayer "smplayer" /usr/bin/smplayer

I meant start of the programs having own settings of "only one instance".
[![2018-10-23-220501-759x475-scrot.png](https://i.postimg.cc/kgkYTZcy/2018-10-23-220501-759x475-scrot.png)](https://postimg.cc/mPySDmKc)
> Can you make a screencast/video?

https://i.postimg.cc/g0w7Hh61/screencast.gif

**Comment by gijsbers** [comment] 2018-10-24 16:37
So if I understand you then you configure smplayer to run once,
but smplayer is running twice and then you ask icewm to fix this?

Thanks for your screencast. It is very strange that if you
switch workspaces that the Process Status also appears
on the new workspace. Icewm does not do this normally.

Does FocusCurrentWorkspace work correctly?

**Comment by arsonoff** [comment] 2018-10-24 17:47
smplayer, with the established option "Use only one running instance", works correctly (only one copy is started). Incorrectly there is the switching of the smplayer window to another workspace (it is necessary to click in addition the taskbar).

The "Process Status" window switches correctly, just it loses Focus if at its switching, on current workspace, the active window of other application (libreoffice, gimp, seamonkey):
```
$ xev -id 0x40005a -event focus

FocusIn event, serial 18, synthetic NO, window 0x40005a,
    mode NotifyNormal, detail NotifyNonlinear

FocusOut event, serial 18, synthetic NO, window 0x40005a,
    mode NotifyNormal, detail NotifyNonlinear
```
Probability of loss of focus not of 100% (> 90%). But I did not understand the reason.

**Comment by arsonoff** [comment] 2018-10-24 20:24
> Does FocusCurrentWorkspace work correctly?

IceWM 1.4.2.1647 - OK

**Comment by gijsbers** [comment] 2018-10-24 20:54
> Incorrectly there is the switching of the smplayer window to another workspace (it is necessary to click in addition the taskbar).

smplayer only sets the urgent hint. It doesn't request focus. So this is correct behavior of icewm.

> it loses Focus if at its switching, on current workspace, the active window of other application

In the screencast the mouse clicks on workspace 2 to switch workspace to 2.
But then suddenly the Process Status appears unexpectedly. There was no mouse click on CPU to make the switch.

**Comment by arsonoff** [comment] 2018-10-24 22:26
Scenario of screencast:
It is active Workspace _2
Programs are started: urxvt with ffmpeg, "Process status"
I switch on workspace _1
Programs are started: urxvt with xev (0xc00022 it is "Process Status"), Seamonkey
I switch to Seamonkey, I start "Process status"
There is "Process status" without focus,
xev writes: "FocusIn..., FocusOut..."
I switch on Workspace _2, I interrupt ffmpeg.
The end.

**Comment by arsonoff** [comment] 2018-10-24 23:12
> smplayer only sets the urgent hint. It doesn't request focus.

But when smplayer on current workspace, icewm switches to it focus.

> Does FocusCurrentWorkspace work correctly?

Oh, smplayer began to switch back incorrectly.
Before the last corrections it though on click, but switched to current workspace.
And now back, on click switches workspace :(

**Comment by gijsbers** [comment] 2018-10-25 03:42
> But when smplayer on current workspace, icewm switches to it focus.

Yes of course then smplayer asks for focus.

> Oh, smplayer began to switch back incorrectly.

You said "I consider that the action given options is too global."
Is "too global" also for task buttons? Now no switch if flashing. Better?

**Comment by arsonoff** [comment] 2018-10-26 00:52
>Better?

Yes

Bug:
- workspace1: one application is started (it is unimportant what, the main thing is the window)
- start of smplayer, through the context menu its transfer on workspace2
- start of smplayer - nothing (!?)
- move the existing window
- start of smplayer - OK, smplayer started blinking on taskbar 

Really implementation of "only one instance" in smplayer (xnviewmp, qbittorrent) so curve what it is impossible to switch normally the window to another workspace?

In JWM smplayer, xnviewmp work correctly (!?), switch between workspaces without blinkings/warnings.

Maybe it is worth bringing in icewm the utility or the option to winoptions that it was possible, by method, compatible with icewm, to start runonce-programs from the file managers, scripts, desktop-files, etc.?

**Comment by gijsbers** [comment] 2018-10-26 08:29
Can you make a screencast of the Bug?

You can use something like the following runonce script.
Modify to your needs.

```bash
#!/bin/bash
#
# Usage: runonce wmclass program arguments
#
# Instead of "wmctrl -R" you can also do "wmctrl -a".
#

wmclass=$1
shift

temp=$(mktemp)
trap 'rm -f $temp' 0

wmctrl -l -x >$temp

while read window workspace class host title
do
    if [[ $class =~ $wmclass ]]
    then
        echo "found window $window $class"
        exec wmctrl -i -R $window
    else
        echo "ignoring window $window $class"
    fi
done <$temp 

exec "$@"
```

**Comment by arsonoff** [comment] 2018-10-26 17:58
> Can you make a screencast of the Bug?

https://i.postimg.cc/504Q0rCL/screencast.gif

**Comment by gijsbers** [comment] 2018-10-27 03:47
Thanks for the screencast!
Set FocusOnAppRaise=1 for JWM behavior.

**Closed as completed** 2018-12-19 20:59 UTC
Labels: bug
