### ISSUE TITLE
broken tray (2)

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/icewm#265] opened 2018-05-01 01:33 UTC
1) osmo-0.4.2 - does not want to be placed in a tray, despite settings.
last good commit - 36fdf5b (392e83b - it is not compiled, 604315f - bad)

2) pidgin-2.10.11 - after restart of icewm, restore the window from a tray.
Icewm 1.4.2 (54dcb3a) - OK
Other programs (qbittorrent, keepassx) - OK
commit 405aba2: before it - problems with an icon in a tray, after it - a problem with recovery of a window from a tray.

**Comment by arsonoff** [comment] 2018-05-01 10:52
osmo works. pidgin became worse.

If at first to start pidgin, and then osmo, then the icon of pidgin vanishes.
Pidgin remains in a tray, takes the place and works, but icons it is not visible.
At restart of icewm the icon of pidgin appears.

**Comment by gijsbers** [comment] 2018-05-01 17:05
Works now, but by hovering the corner of a window over the pidgin icon you can see that it doesn't respond to expose events, which looks like a GTK bug.

**Comment by arsonoff** [comment] 2018-05-04 13:22
The bug became more cunning. Now the icon vanishes at start not of one, but two programs: pidgin, osmo, qbittorent... pidgin disappeared.
The pidgin window everything also emerges after restart of icewm.

**Comment by arsonoff** [comment] 2018-05-08 14:27
Icons ceased to disappear.
But there were problems at restart of icewm:
pidgin - restore the window from a tray (with probability of >95%, it is sometimes normal)
qbittorrent - artifacts on an icon (with probability of 30-35%: the background changes; there are pieces of other icon)
[![qbittorrent.png](https://s7.postimg.cc/lnbpoer6j/qbittorrent.png)](https://postimg.cc/image/p6xne7tw7/)

**Comment by gijsbers** [comment] 2018-05-08 20:22
Can't reproduce it. Always works fine 100%.

**Comment by arsonoff** [comment] 2018-05-09 01:59
qbittorrent.
found two reasons: compton - gives the background (often), keepassx started later  qbittorent (it is not obligatory for the following) spoils to it the icon (sometimes).

pidgin.
The problem is probably related with the fact that after restart of icewm the pidgin window becomes in focus (if not to minimize pidgin, then focus from the active window passes to pidgin)

Question:
Why now icewmtray and the options TaskBarShowTray, TaskBarEnableSystemTray is necessary?
I start icewm or icewm-session with "--notray" - the tray works.
At this icewmtray it is not started, in start attempt just comes to the end.
TaskBarShowTray=0 - does not influence.
TaskBarEnableSystemTray=0 - crash icewm.

**Comment by gijsbers** [comment] 2018-05-09 20:17
You didn't mention you were using compton. With compton I can reproduce it. Therefore it is a bug in compton and/or in qbittorrent and you should report there and not here.

Answer:
there are two trays, TaskBarShowTray applies to the first while TaskBarEnableSystemTray to the second. --notray is for external system trays and is now obsolete. I've fixed the crash.

**Comment by arsonoff** [comment] 2018-05-10 10:38
qbittorrent:
compton is responsible only for the half of the bug.
The linking of qbittorrent/keepassx is buggy at default settings and without compton (the bug is shown in 10-20% of cases of restart of icewm)
In release 1.4.2 - it works correctly (with compton).

pidgin:
Why the icewmtray program in the latest version icewm is necessary? I cannot start it.
Before commit 405aba2 when icewm-session started process of icewmtray, pidgin did not restore from the tray at restart of icewm.

**Comment by bbidulock** [comment] 2018-05-11 01:34
Its a bug.  Icewm tray come nowhere close to performing the proper fdo systray protocol.

**Comment by zaza42** [comment] 2018-09-11 01:54
Recompile pidgin with `--enable-trayicon-compat` parameter, then the tray works normally.

**Comment by arsonoff** [comment] 2018-09-21 01:15
```
--enable-trayicon-compat
                        install tray icons in location compatible with older
                        releases of hicolor-icon-theme 
```
This option in any way did not affect behavior of pidgin (pidgin-2.10.11 (and 2.13), icewm-1.4.2.1550) - after restart of icewm, pidgin restore the window from a tray.

**Comment by bbidulock** [comment] 2018-09-21 20:03
It likely does this because the tray is now part of icewm.  Before it was a separate program and icewm could restart without disrupting the tray.  As a result of including it in icewm, when icewm restarts, the system tray goes away and then comes back later after restart.  Pidgin likely sees the system tray disappear and thus opens its window because there is no place to put its icon.  When the tray comes back and it installs its icon in the system tray, it does not drop the window that it popped.  Sounds to me like that is the way the application was designed to work, and there is little that icewm can do about it:  splitting off the panel again has other issues associated with it that were best addressed by including it in icewm.

**Comment by arsonoff** [comment] 2018-10-23 05:27
The remained problems of course small, restart icewm not such frequent transaction in daily work. Especially as problems only with some specific applications. 

And it is possible to make by analogy with startrup/shutdown scripts the scripts which are carried out before restart and after restart?

**Comment by gijsbers** [comment] 2018-10-24 16:34
> startrup/shutdown scripts

For icewm you can easily write a script to monitor the
startup/restart/shutdown events and execute your scripts:

```bash
#!/bin/bash
xprop -root -spy ICEWM_GUI_EVENT |
    while read a b c; do
        if [[ $c = 0x0 ]]; then
            echo startup;
        elif [[ $c = 0x2 || $c = 0x1 ]]; then
            echo shutdown;
        fi;
    done 
```

Is this broken tray issue done?

**Closed as completed** 2018-10-24 20:21 UTC
Labels: bug
