### ISSUE TITLE
Remember tab order through restart

### ISSUE THREAD

**Issue by jidanni** [bbidulock/icewm#477] opened 2020-08-25 00:37 UTC
1. Note the order of the tabs at the bottom of the screen.
2. Press Restart Icewm from the menu.
1. Note again the order of the tabs at the bottom of the screen.

(There's a big chance that:) They have changed!

Icewm remembers that we had a chromium tab, a firefox tab, etc. and restores them. Well it should also remember their order!

Else grandma, who always had firefox on the left, and chromium on the right, will be confused and unable to work happily for the rest of the day!

**Comment by zaza42** [comment] 2020-08-25 03:06
duplicate of [#452](https://github.com/bbidulock/icewm/issues/452)

**Closed as completed** 2020-08-25 17:23 UTC
Labels: duplicate
