### ISSUE TITLE
icesh move and setGeometry don't recognize decorations of Qt apps

### ISSUE THREAD

**Issue by E5ten** [bbidulock/icewm#351] opened 2019-06-07 16:12 UTC
When I move a Qt application using icesh move or setGeometry, the point I select is where the top left of the app not counting the titlebar or borders goes, whereas with anything else the point is where the top left of the titlebar goes.

**Comment by gijsbers** [comment] 2019-06-08 06:19
Why is this problematic? What is your recommendation?

**Comment by E5ten** [comment] 2019-06-09 17:56
In terms of scripting window movement keybinds with icesh (which is my usecase here), the windows need to move consistently, it doesn't work if some move to the top left outside the decorations and some move to the top left inside the decorations. In terms of a recommendation, I have no idea how to fix this, but I figured I'd report it anyway in case someone familiar with the codebase had an idea.

**Comment by bbidulock** [comment] 2019-06-10 06:42
What is window gravity on the two windows that you are comparing?

**Comment by E5ten** [comment] 2019-06-10 22:28
Ah that does seem like it should be the issue, in xprop every Qt app I check has `window gravity: Static` while others don't.

**Comment by bbidulock** [comment] 2019-06-10 22:47
The behavior is then correct, given the window gravity setting.

**Comment by ghost** [comment] 2019-06-15 14:00
One longstanding problem is that Qt applications have problems restoring their previous window state on IceWM. They get the maximized state wrong, or the exact position of the window. (Something like that, it's not supposed to be an exhaustive description of the issue.) Is that related?

**Comment by gijsbers** [comment] 2019-06-15 17:05
Seems like a different issue related to session management. Feel welcome to file an issue, but please add a clear reproducible scenario, or two.

**Comment by gijsbers** [comment] 2019-06-19 12:49
Why do you wonder about relatedness? If you assume a problem then it is best to open your own issue, so @E5ten can feel free to close this one.

**Comment by ghost** [comment] 2019-06-19 15:50
Right, I'll report it as new issue as soon as I spot an easily reproducible case.

**Closed as completed** 2019-06-19 16:54 UTC

**Comment by E5ten** [comment] 2019-07-22 17:54
I wonder if it would be possible to add to icesh support for getting/setting window gravity, so that in my scripted basic tiling instead of putting in manual overrides for all my Qt apps I could check the window gravity and change behaviour based on that, or set the window gravity to 0 so behaviour doesn't have to be changed?

**Comment by gijsbers** [comment] 2019-07-23 08:46
Thanks for your useful suggestion! I added it. Could you perhaps share your scripted basic tiling?

**Comment by E5ten** [comment] 2019-07-23 18:18
@gijsbers despite xprop having output like
```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified size: 1914 by 1015
		program specified minimum size: 300 by 135
		window gravity: Static
```
(aside from differences in the numbers for the size parts) for Qt app windows, icesh and getWindowGravity report NorthWestGravity for those windows, and setting the gravity with icesh doesn't seem to change the behaviour to include the decorations when moving or setting geometry.

**Comment by bbidulock** [comment] 2019-07-23 19:20
Gravity is a hint to the window manager when a window is mapped.  I made most of these window managers set NorthWestGravity on every window when it is initially managed by the window manager as handling various gravities is difficult to get correct.  The client toolkit is supposed to examine window gravity when the window is initially mapped and use the gravity set by the window manager.  Changing gravity after the window is initially mapped will likely not change anything as the window manager sets gravity only when initially managing and mapping a window.  The toolkit need not check it further.

That you see NorthWestGravity does not mean that was what the toolkit set in the first place.  The window manager sets NorthWestGravity always when initially mapping the top level window.  If Qt is not handling decorations correctly, it is likely because it is not examining window gravity after the window is initially mapped.

**Comment by gijsbers** [comment] 2019-07-23 20:34
I tried this commit on a Qt application and it plain works.
IceWM reloads WM_NORMAL_HINTS when it is updated.

I assume you use the `setGeometry` of icesh.
Other means to position windows with icesh are implemented differently.
 Like `move`, `left` and `top`. They may give better results.

**Comment by E5ten** [comment] 2019-07-24 00:41
setNormalGravity works perfectly, thanks for implementing it. In terms of my tiling script it is based on the one in #335, I'm happy that it's now at a place where the whole script can work with only a single external command that manages the entire movement and resizing process (I replaced the xrandr for res checking with hardcoded values in the variables because I'm using it locally anyway and wanted to minimize external command calling).
```
#!/bin/sh

# change hardcoded values as necessary
FULLW=1920 # full screen width
FULLH=1080 # full screen height
TASKH=40   # taskbar height
BORDER=3   # border width/height
TBARH=19   # titlebar height

: "$((FULLH -= TASKH))"

case "$1" in
    top)     W="${FULLW}"       H="$((FULLH / 2))" X=0      Y=0     ;;
    bottom)  W="${FULLW}"       H="$((FULLH / 2))" X=0      Y="${H}";;
    max)     W="${FULLW}"       H="${FULLH}"       X=0      Y=0     ;;
    left)    W="$((FULLW / 2))" H="${FULLH}"       X=0      Y=0     ;;
    right)   W="$((FULLW / 2))" H="${FULLH}"       X="${W}" Y=0     ;;
    tleft)   W="$((FULLW / 2))" H="$((FULLH / 2))" X=0      Y=0     ;;
    tright)  W="$((FULLW / 2))" H="$((FULLH / 2))" X="${W}" Y=0     ;;
    bleft)   W="$((FULLW / 2))" H="$((FULLH / 2))" X=0      Y="${H}";;
    bright)  W="$((FULLW / 2))" H="$((FULLH / 2))" X="${W}" Y="${H}";;
esac

: "$((W -= BORDER * 2))"
: "$((H -= BORDER * 2 + TBARH))"

# disable maximized attributes with restore, set gravity to NorthWest so window
# decorations are never cut off and finally move and resize the window
icesh -f restore setNormalGravity NorthWestGravity setGeometry "${W}x${H}+${X}+${Y}"
```
