### ISSUE TITLE
The system tray ramdomly shows in different behavior

### ISSUE THREAD

**Issue by ghost** [bbidulock/icewm#193] opened 2017-10-26 08:33 UTC
This has been bugged me for a while, that the systray randomly doesn't show in the left side of battery, but show as a window: 
![odd](https://user-images.githubusercontent.com/7656607/32042698-002e773c-ba6b-11e7-8e6a-29da6f910ec2.png)

OS: PCLinuxOS
IceWM: 1.4.2

I've found this problem is not distro specified, but icewm itself, because on CRUX GNU/Linux and Gentoo Linux, I also have this issue. Could anyone point out why and how to fix this?

**Comment by gijsbers** [comment] 2017-10-26 10:09
Probably related to issue #152.
A lot of work has gone into icewmtray since then.
Did you try the current source tree?
Try to get this:
```
$ xprop -root | grep 'CHECK.*window' | awk '{print $NF}' | xargs xprop -id | grep WM_NAME
_NET_WM_NAME(UTF8_STRING) = "IceWM 1.4.2.647 (linux-gnu/x86_64)"
WM_NAME(STRING) = "IceWM 1.4.2.647 (linux-gnu/x86_64)"
```

**Comment by SolisX** [comment] 2017-10-26 18:05
Hello Everyone,

@rtlanceroad You can try adding "sleep 2" before your startup programs.

example: In your ~/.icewm/startup add.

sleep 2
wicd-client -t &
pasystray &

**Comment by ghost** [comment] 2017-10-27 05:57
@gijsbers Since I don't have permission to commit changes to PCLInuxOS repository, I have to compile IceWM locally. But I can't compile it using current source tree with gcc-c++-7.2.1:

```
[guest@localhost icewm-icewm-1-4-BRANCH]$ make V=0
make  all-recursive
make[1]: Entering directory '/union/home/guest/icewm-icewm-1-4-BRANCH'
Making all in src
make[2]: Entering directory '/union/home/guest/icewm-icewm-1-4-BRANCH/src'
  CXX      mstring.lo
In file included from mstring.cc:6:0:
../config.h:538:16: error: duplicate ‘unsigned’
 #define size_t unsigned int
                ^
../config.h:538:25: error: multiple types in one declaration
 #define size_t unsigned int
                         ^
../config.h:538:25: error: declaration does not declare anything [-fpermissive]
../config.h:532:15: error: multiple types in one declaration
 #define pid_t int
               ^
../config.h:532:15: error: declaration does not declare anything [-fpermissive]
In file included from /union/usr/include/c++/7.2.1/stdlib.h:36:0,
                 from mstring.cc:10:
/union/usr/include/c++/7.2.1/cstdlib:145:11: error: ‘::malloc’ has not been decl
ared
   using ::malloc;
           ^~~~~~
/union/usr/include/c++/7.2.1/cstdlib:158:11: error: ‘::realloc’ has not been dec
lared
   using ::realloc;
           ^~~~~~~
In file included from mstring.cc:10:0:
/union/usr/include/c++/7.2.1/stdlib.h:65:12: error: ‘std::malloc’ has not been d
eclared
 using std::malloc;
            ^~~~~~
/union/usr/include/c++/7.2.1/stdlib.h:73:12: error: ‘std::realloc’ has not been                               declared
 using std::realloc;
            ^~~~~~~
mstring.cc: In static member function ‘static MStringData* MStringData::alloc(in                              t)’:
mstring.cc:17:39: error: ‘malloc’ was not declared in this scope
     MStringData *ud = (MStringData *) malloc(size);
                                       ^~~~~~
mstring.cc:17:39: note: suggested alternative: ‘alloc’
     MStringData *ud = (MStringData *) malloc(size);
                                       ^~~~~~
                                       alloc
Makefile:1555: recipe for target 'mstring.lo' failed
make[2]: *** [mstring.lo] Error 1
make[2]: Leaving directory '/union/home/guest/icewm-icewm-1-4-BRANCH/src'
Makefile:582: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/union/home/guest/icewm-icewm-1-4-BRANCH'
Makefile:464: recipe for target 'all' failed
make: *** [all] Error 2
```

So I can't say.

@SolisX I have that with 5 seconds to wait, but It doesn't work sometimes, wrt the IceWM tray. It may work with 3rd party systray I guess.

**Comment by gijsbers** [comment] 2017-10-27 06:32
@rtlanceroad Apparently your `config.h` has a definition `#define size_t unsigned int`. This is silly. Two options:
* Try without that line and change it into: `/* #define size_t unsigned int */`
* Remove the `int`: #define size_t unsigned

**Comment by bbidulock** [comment] 2017-10-27 07:19
@rtlanceroad   Looks like your gcc compiler is a broken one or something got out of step.  You can try:

    autoreconf -fiv
    ./configure.sh
    make clean
    make V=0

maybe even in a clean new working directory.

**Comment by bbidulock** [comment] 2017-10-27 07:34
With regard to the issue: it happens to me sometimes too.  @Code7R fixed some of the startup code.  The system tray in IceWM is separate from the window manager: it is the icewmtray program.  If it starts before icewm initializes its internal tray (and takes ownership of the _ICEWM_INTTRAY_S%d  manager selection) it starts on its own.  I don't think that anyone wants it outside the task bar anymore, so I will make it wait for it to appear before it tries to embed itself.  Or, just throw away icewmtray altogether and put the code directly into icewm.

**Comment by ghost** [comment] 2017-10-27 08:08
@gijsbers Thank you. I followed advice from @bbidulock and it never appears. But gcc-c++-7.2.1 throwed me more declaration conflict problems, and I don't want to bother your guys about my compiling issues. With regard to IceWM tray, since it's confirmed, I'll wait for the fixes from you guys hopefully in the next release.

**Comment by Code7R** [comment] 2017-11-04 10:49
The problem with tray startup which looked like a race is probably not fully fixed. I still see this issue from time to time. About once per month... still better than almost every day as it was before on the same system, but the origin is still not very clear to me.

**Comment by gijsbers** [comment] 2017-11-15 20:35
This issue and all comments should be fixed now.

**Comment by Code7R** [comment] 2017-11-25 16:08
Well, sorry to tell you but I just tested latest HEAD and can still observe it. Easy to reproduce: start pasystray three times, then kill two of the processes.
Result:
![garbled_tray_icons_remain](https://user-images.githubusercontent.com/10660264/33232264-2798d5a6-d203-11e7-8db2-5c520b0787a4.png)

**Comment by gijsbers** [comment] 2017-11-25 16:45
Tried twice to reproduce, but works fine for me. I assume you no longer run the external tray process, but use the internal tray.

**Comment by Code7R** [comment] 2017-11-25 17:33
Oh, ok. It seems to work when configured with autoconf.

Must be one of those subtle differences. I guess I will fix by myself, since there is another change I needed to apply anyway, and also review the needed changes WRT the proposed gdx-pixbuf removal (at least what I have seen up in recent commits).

Stay tuned...

**Comment by gijsbers** [comment] 2017-11-27 21:38
@rtlanceroad Does it work for you as well now?

**Comment by ghost** [comment] 2017-11-30 11:56
@gijsbers Sorry for late reply. I built icewm from latest HEAD, relogin and reboot for nearly 20 times it no longer shows as a windows. But some other problem appears:
![problem](https://user-images.githubusercontent.com/7656607/33429275-217d587e-d607-11e7-8b18-4e60f164cfae.png)

- The desktop switching from one to another is very very slow, I click another desktop 9 times and about 15 seconds, it finally switched...
- You see from the picture, I am working on desktop A, urxvt is working and desktop A is highlighted with square, but the strange part is the urxvt window is thumbnail-ed on desktop B... 

Hopefully these can be fixed.

**Comment by ghost** [comment] 2017-11-30 12:09
Sometimes the switch lasts longer than 1 minutes and no response for you...

**Comment by gijsbers** [comment] 2017-11-30 12:09
@rtlanceroad Thanks! What is the name of the theme you use?
1. Does icewm produce any interesting errors for this slow desktop switching?
2. This may be normal. If you go to workspace B will you still see the urxvt?
You can play with this via the window menu "Occupy All", "Move To" and the ~/.icewm/winoptions.

**Comment by ghost** [comment] 2017-11-30 12:47
@gijsbers The theme is from [here](https://www.box-look.org/p/1018053/). 

   1. I don't see anything from terminal after I logout. And I don't have a logger on this system.
   2. Yes, I can see urxvt when I switch to B. I don't have ~/.icewm/winoptions setup for use, and I  
       didn't do any thing to urxvt expect just open it using keybinding. so I thought it should have been
       thumbnail-ed in the original workspace.

**Comment by gijsbers** [comment] 2017-11-30 13:08
@rtlanceroad 
1. Usually the output of a window manager is redirected to a file in your home directory like `~/.xinitrc.log` or `~/.xsession-errors`. Try `ls -ltrac ~` to see it. Otherwise replace the icewm executable with something similar to:

    mv icewm icewm.bin
    cat >icewm <<EOF
    #!/bin/sh
    exec "$0".bin "$@" >> ~/icewm.out 2>&1
    EOF
    chmod 755 icewm

2. It's not a thumbnail. It's a workspace preview. Try opening multiple terminals and applications in different workspaces.

**Comment by ghost** [comment] 2017-11-30 13:14
Wait a minute... My stupidity... After I switched to default theme, I found the hightlighted workspace with square is actually not my current workspace, so that's why it doesn't respond when I click on it. Sorry guys. I didn't drink wine today but I made a mistake. Anyway the issue at least for me is resolved.

**Comment by gijsbers** [comment] 2017-11-30 13:17
Okay. If you're happy please close this issue.

**Closed as completed** 2017-11-30 13:21 UTC
Labels: bug
