### ISSUE TITLE
ShowEllipsis option meaning

### ISSUE THREAD

**Issue by DieSpinne** [bbidulock/icewm#500] opened 2020-10-07 19:44 UTC
Sorry if this is obvious, but I can't find out what ShowEllipsis option means. The description is "Show Ellipsis in taskbar items", but it does not help much. I have turned it on and off, but couldn't detect any change in the taskbar. Can you please clarify it? Thanks!

**Comment by Code7R** [comment] 2020-10-08 08:17
It's just an optical helper to see that some menus contain further entries which follow a certain pattern, i.e. start with that prefix.

For example, you can see the difference in the Themes menu, however it only becomes visible when the automatic nesting triggers, which only happens when you have very many themes installed. To play with this, you could set the NestedThemeMenuMinNumber to something low, like 7.

Another examples are window titles in the taskbar. Once you get it full so that the name does not fit, it will truncate it and show an ellipsis indicator or just truncate.

But I will improve the description of ShowEllipsis option.

**Comment by Code7R** [comment] 2020-10-08 08:31
PS: @gijsbers I see at least one bug in Graphics::drawStringEllipsis and the option seems to be not effective anymore. Something was messy with commit 941d40afb8cb16d9c381af0f93ced7eff96d52ce , I need to double-check.
Edit: actually, this is not a bug, just wasted CPU call. But the method is not clever, runs in O(n), can be changed to O(log n)

**Comment by DieSpinne** [comment] 2020-10-08 13:04
Dear Lord! I was thinking of ellipses rather than ellipsis. Thank you for the explanation, I could verify the described behavior.

**Comment by Code7R** [comment] 2020-10-30 20:58
I think the latest changes were enough, and the reporter seems to be satisfied. Closing.

**Closed as completed by Code7R** 2020-10-30 20:58 UTC
