### ISSUE TITLE
KeyTaskBarSwitch{Next|Prev} wrong order

### ISSUE THREAD

**Issue by ithgub** [bbidulock/icewm#605] opened 2021-07-29 09:45 UTC
KeyTaskBarSwitchNext & KeyTaskBarSwitchPrev do not take into account that the order of Task Bar buttons of open windows changes when user drag-n-drops (moves with a mouse) a Task Bar button. Then, instead of switching to the right/left (Next/Prev) window as they are represented at the Task Bar, the original Task Bar buttons order is used, and windows switch in an unexpected, confusing and undesirable order

**Comment by gijsbers** [comment] 2021-07-29 17:58
Thanks for reporting this! But is it a duplicate of #602 and:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=991153

**Comment by gijsbers** [comment] 2021-08-06 12:33
Fixed by 2.7.0.

**Closed by gijsbers** 2021-08-06 12:33 UTC
Labels: duplicate
