### ISSUE TITLE
Two icons superimposed

### ISSUE THREAD

**Issue by jidanni** [bbidulock/icewm#188] opened 2017-10-20 08:51 UTC
A new dead status icon has appeared when I connect to the network.
![k](https://user-images.githubusercontent.com/1230959/31812771-ae117d54-b5b6-11e7-93cb-781161baf37f.jpg)
It is just to the right of "EN" above.

Unlike the other icons, putting the mouse upon it does not create any pop-up explanation of what it is all about.

In fact it seems quite dead. Maybe it is.

**Comment by Code7R** [comment] 2017-10-22 08:51
Please show the output of:

cat /proc/net/dev

ip link

**Comment by jidanni** [comment] 2017-10-22 21:30
```
$ cat /proc/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo:  520401    1604    0    0    0     0          0         0   520401    1604    0    0    0     0       0          0
wlp2s0b1:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
enp1s0: 149899665  108492    0    0    0     0          0         0  6876084   68889    0    0    0     0       0          0
  ppp0: 147510463  108431    0    0    0     0          0         0  5352451   68759    0    0    0     0       0          0
$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 20:89:84:28:0a:d9 brd ff:ff:ff:ff:ff:ff
3: wlp2s0b1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:3e:8e:aa:65:d1 brd ff:ff:ff:ff:ff:ff
4: ppp0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1492 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 3
    link/ppp 
```
which corresponds to
![m](https://user-images.githubusercontent.com/1230959/31866514-1463fd04-b7b3-11e7-9068-719174b4e94f.jpg)
So the left box, which indeed changes every few minutes, is some sort of compost of the other boxes it seems. But without any mouseover, the user doesn't know.

**Comment by bbidulock** [comment] 2017-10-22 21:51
Please run:

    xwininfo -tree

and click the cross-hairs on the task bar over the icon and find the id of that window.  Then do

    xprop -id 0x00dead01

with the id of the window to get all its properties.

IceWM does not support the XEmbed protocol on  systray icons (as it should).  Some icon might be requesting to be unmapped by setting XEMBED_MAPPED to 0 in _XEMBED_INFO and then not honoring exposure events on its ParentRelative window.  Can generate garbage where it would be.

**Comment by jidanni** [comment] 2017-10-23 10:37
It turns out the mystery box is just the right part of the ibus pair of
boxes that live in the bar at the bottom of the screen.

The left box has EN in it usually, as you can see in my uploads.

Anyway when I hit CTRL+SPACE the right one toggles back and forth to
several pieces of garbage found around the screen. So sometimes it
contains part of icewm's meters. Sometimes it contains an icon from the
upper right corner, etc. Seems rather random.

All this started happening when I upgraded icewm. Ibus has had no recent upgrades.

```xwininfo -tree```

just gives the same results no matter where on that long horizontal bar
that spans the bottom of the screen I click it.

I.e., the box is not a window, but just a box living in the bar at the
bottom of the screen.

But here you go anyway.

```xwininfo -tree

xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0xa00092 (has no name)

  Root window id: 0x108 (the root window) (has no name)
  Parent window id: 0xa000b2 (has no name)
     15 children:
     0xa000c3 (has no name): ()  999x21+158+3  +158+745
     0xa000c2 (has no name): ()  999x25+158+1  +158+743
        3 children:
        0xa00305 (has no name): ()  332x25+665+0  +823+743
        0xa001fe (has no name): ()  332x25+333+0  +491+743
        0xa0019e (has no name): ()  333x25+0+0  +158+743
     0xa000c1 (has no name): ()  1x25+1158+1  +1158+743
     0xa000c0 (has no name): ()  10x20+1212+3  +1212+745
     0xa000bf (has no name): ()  16x16+1271+5  +1271+747
     0xa000be (has no name): ()  1x25+107+1  +107+743
     0xa000bd (has no name): ()  25x25+78+1  +78+743
     0xa000bc (has no name): ()  25x25+53+1  +53+743
     0xa000bb (has no name): ()  53x25+0+1  +0+743
     0xa000a7 (has no name): ()  48x24+1161+1  +1161+743
        1 child:
        0xa0010c (has no name): ()  48x24+0+0  +1161+743
           1 child:
           0xc00005 (has no name): ()  48x24+0+0  +1161+743
              1 child:
              0xc00006 (has no name): ()  48x24+0+0  +1161+743
                 2 children:
                 0xc0011c (has no name): ()  24x24+24+0  +1185+743
                 0xc0000c (has no name): ()  24x24+0+0  +1161+743
                    1 child:
                    0x1000007 "IBus Panel": ("ibus-ui-gtk" "ibus-ui-gtk")  24x24+0+0  +1161+743
                       1 child:
                       0x1000008 (has no name): ()  1x1+-1+-1  +1160+742
     0xa000a5 (has no name): ()  42x25+112+1  +112+743
        1 child:
        0xa000a6 (has no name): ()  42x25+0+0  +112+743
     0xa0009d (has no name): ()  74x20+1290+3  +1290+745
     0xa00099 (has no name): ()  20x20+1200+3  +1200+745
     0xa00097 (has no name): ()  20x20+1248+3  +1248+745
     0xa00094 (has no name): ()  20x20+1224+3  +1224+745
```

No I don't know how to get the coordinates of where I put the
crosshairs, so cannot tell you exactly which one it is.

**Comment by bbidulock** [comment] 2017-10-23 12:46
The mystery box is the 0xc0011c window, which seems to have lost its system tray icon child without going away.  Shouldn't happen, but, there it is.  I will investigate.  Thank you for the output.

**Comment by bbidulock** [comment] 2017-10-23 15:02
Tray this latest commit c02457a and see if it fixes the problem.

**Comment by jidanni** [comment] 2017-10-31 01:10
Thanks. (I will wait until there is a .deb...)

**Comment by Code7R** [comment] 2017-11-09 13:28
I prepared the debs but I'd prefer not to release them. Reason: there is a new issue with the tray, looks like the background is not painted anymore and contains some pixmap garbage instead (maybe from pixbuf cache?).
Quick check with valgrind does not reveal anything, though.
![garbled_icewmtray_background](https://user-images.githubusercontent.com/10660264/32607744-376c268c-c55a-11e7-8a76-664d3836447f.png)

**Comment by jidanni** [comment] 2017-11-10 13:04
Yes... indeed my little square(s) of pixmap garbage is quite interesting
sometimes... snowflakes, etc. Sort of like "little squares of 'blotter
acid'" (LSD).

**Comment by Code7R** [comment] 2017-11-10 13:09
So, again, I did not feel safe regarding this issue and had the impression that this is some kind of resource allocation/invalidation issue since we apparently see random fragments of other windows pixmaps there. So I made little digging (debug build) and observed something more disturbing. Example: start icewmtray, start icewm, start pasystray. Close pasystray via its menu. Move the mouse again on the space where the icon previously was - you see debug notifications like those:

```
icewmtray: window=0x200018: enterNotify serial=       391 root=0x26D, subwindow=0x0, time=4083165, (0:5 447:461) mode=0 detail=0 same_screen=True, focus=False state=0x0
icewmtray: window=0x200018: leaveNotify serial=       391 root=0x26D, subwindow=0x0, time=4083779, (-2:5 445:461) mode=0 detail=0 same_screen=True, focus=False state=0x0
icewmtray: window=0x200013: leaveNotify serial=       391 root=0x26D, subwindow=0x200018, time=4083779, (-2:5 445:461) mode=0 detail=1 same_screen=True, focus=False state=0x0
icewmtray: window=0x200012: leaveNotify serial=       391 root=0x26D, subwindow=0x200013, time=4083779, (-2:5 445:461) mode=0 detail=1 same_screen=True, focus=False state=0x0

``` 

So basically there is some dead window handle from the closed icon still active. Maybe also from shifted icons? Anyhow, I bisected this, leading to:

```
61c65d5d317af1861e299be51edf0dfaa93f3c9a is the first bad commit
commit 61c65d5d317af1861e299be51edf0dfaa93f3c9a
Author: Bert Gijsbers <gijsbers@science.uva.nl>
Date:   Thu Sep 21 23:56:12 2017 +0200

    Changes to tray. Solutions for bug #152.

:040000 040000 a38b4ebd24766a69ecc91bd387c678b2e0b98700 ce431d18e2267f5372d5d2313679ce75bbbc89b9 M	src

```

I still have no proof but my gut feeling says that multiple issues originate from there, @jidanni 's dead status icon (just a ghost), the pixmap garbage mentioned above and the "small icon pasted over" effect which I remember to have reported as issue some weeks ago which also disappeared like a ghost.

**Comment by jidanni** [comment] 2017-11-10 13:46
By the way,
$ sort -u .xsession-errors
IceWM: Warning: X error X_ChangeSaveSet(0x1E00011): BadWindow (invalid Window parameter)
IceWM: Warning: X error X_ChangeSaveSet(0xA00092): BadMatch (invalid parameter attributes)
IceWM: Warning: X error X_ChangeWindowAttributes(0x1E00011): BadWindow (invalid Window parameter)
IceWM: Warning: X error X_ChangeWindowAttributes(0x400000): BadWindow (invalid Window parameter)
IceWM: Warning: X error X_ConfigureWindow(0x0): BadValue (integer parameter out of range for operation)
Not sure if related.

**Comment by gijsbers** [comment] 2017-11-10 17:05
That would be funny since you reported that on July 28 while work on icewmtray started on Sept 21. Nevertheless try and see if the background is now set. Some tray apps like pasystray seem to use a transparent background.

**Comment by jidanni** [comment] 2018-08-25 11:52
Here's what the ibus 1.5.18 icon currently looks like, the blue square with white marks on the left.
![1](https://user-images.githubusercontent.com/1230959/44617980-1bd55680-a8a0-11e8-9552-5743e45a3303.jpg)
I don't think that's what their authors intended but I don't know.

**Comment by gijsbers** [comment] 2018-08-25 12:28
Could you ask them? How else could we know what needs to be done?

**Comment by jidanni** [comment] 2018-08-25 12:41
Wait! I found what the original icon is supposed to look like, I suppose:
![2](https://user-images.githubusercontent.com/1230959/44618358-dbc5a200-a8a6-11e8-953a-8934a331e05b.jpg)
So it is a [酷](http://chewing.im/) character in white on a blue background.
So it is indeed injured, but at least stays in its box...

**Comment by bbidulock** [comment] 2018-08-27 23:45
Looks like the icon just does not scale well.  A slight increase to the panel height?

**Comment by jidanni** [comment] 2018-08-27 23:55
Try this simple test. In your browser click on view the image in https://github.com/bbidulock/icewm/issues/188#issuecomment-415966692
in another window/tab.
Then there use CTRL+------- ... to shrink it.

Nowhere during the process does the insides become as ugly as what we see...

**Comment by gijsbers** [comment] 2018-08-28 15:10
What proves that the image was indeed scaled?
Both seem to have size 28x28.

**Comment by jidanni** [comment] 2018-08-28 15:21
Indeed, the 酷 character got mangled.
![0](https://user-images.githubusercontent.com/1230959/44732971-22bace00-ab19-11e8-85c2-7c64181c8cd6.jpg)

**Comment by gijsbers** [comment] 2018-08-28 16:22
Rather looks like **EN** was written on top of the character.
Nothing was scaled, nothing got mangled, just overwritten.
Doesn't look like an icewm bug to me, or we'd seen this before.

**Comment by jidanni** [comment] 2018-08-29 03:16
Indeed, that makes sense, as I just noticed when I am in Chinese (中) mode, a separate icon appears on the left. 
![0](https://user-images.githubusercontent.com/1230959/44763184-9d690500-ab7c-11e8-9b6a-9e35cce45016.jpg)
So indeed, returning to English mode would probably be indicated by EN, and just as you say, printed on top of it.

**Comment by jidanni** [comment] 2018-08-29 06:57
Indeed, after boot, but before ever switching into Chinese mode, I see a plain "EN":
![0](https://user-images.githubusercontent.com/1230959/44770812-cb117680-ab9b-11e8-9972-48ac3173bbb1.jpg)

**Comment by Code7R** [comment] 2018-09-16 22:05
@jidanni , I am confused. Do we still have the problem in topic (some dead icon?). If yes, can you create an appropriate story? If no, can you close this one?

**Comment by jidanni** [comment] 2018-09-17 03:26
OK I changed the title to reflect what we now know.

**Comment by ithgub** [comment] 2021-05-23 12:58
![scrot 2021-05-23T14:23:32,201906837+03:00](https://user-images.githubusercontent.com/75799052/119259781-66a26b00-bbbf-11eb-83c7-cb5a369a2b28.png)
From left to right, "!"-marked items are the reported ones, "."-marked are OK: 
0 . sunflower file manager on the taskbar 
1 ! lxqt-notificationd — black background 
2 . yad 
3 . geany 
4 ! qbittorrent — you can see pale "qb" which is actual qbittorrent icon on yellow geany magic lamp icon 
5 . zim 
6 ! sunflower — no icon at all, yet it is functional with both left and right mouse button. Sunflower is also shown to the left of the tray on the taskbar (#0 in this list) so that the reader could get how its icon looks like. 
7 . lxqt-powermanagement 
8 ! keepasxc — there is some text below the icon 
9 . clipit 
A ! fbxkb-start — some additional frame in the background 
B . volumeicon 

Also, there is a thin horizontal line at the very bottom of the tray, the lowest pixel row (you might need to zoom in the screenshot to see it). Notice that it is not present on the taskbar itself (where #0 Sunflower is, to the left of the tray) but it blemishes tray through clock.

**Comment by gijsbers** [comment] 2021-05-23 13:47
This is useful, but could you add the output of `icesh -x list` ? That would give more detail to the image.

**Comment by ithgub** [comment] 2021-05-25 15:31
![scrot 2021-05-23T14:23:32,201906837+03:00](https://user-images.githubusercontent.com/75799052/119259781-66a26b00-bbbf-11eb-83c7-cb5a369a2b28.png)
```
> icesh -x list
0x6c0006    0  4378 "lxqt-notificationd": (lxqt-notificationd.lxqt-notificationd) 300x136+974+627
0xc45be7    0 21050 "qBittorrent"       : (qbittorrent.qBittorrent) 337x227+53+22
0xc45be0    0 21050 "qBittorrent"       : (qbittorrent.qBittorrent) 286x203+100+22
0x7000a7    0  4388 "keepassxc"         : (keepassxc.keepassxc) 392x328+6+22
0x70008e    0  4388 "keepassxc"         : (keepassxc.keepassxc) 189x76+57+79
0x7000c5    0  4388 "keepassxc"         : (keepassxc.keepassxc) 161x75+685+205
0x7000be    0  4388 "keepassxc"         : (keepassxc.keepassxc) 132x75+685+180
0x7000b7    0  4388 "keepassxc"         : (keepassxc.keepassxc) 310x250+323+103
0xc48f64    0 21050 "qBittorrent"       : (qbittorrent.qBittorrent) 235x76+203+41
0xc48f6b    0 21050 "qBittorrent"       : (qbittorrent.qBittorrent) 279x102+148+41
0xc453da    0 21050 "qBittorrent"       : (qbittorrent.qBittorrent) 298x229+923+540
0xc4a235    0 21050 "qBittorrent"       : (qbittorrent.qBittorrent) 491x20+442+364
0xa40006    0  7174 "fish /home/olve"   : (qterminal.qterminal) 1280x769+0+0
0x8c0006    0  6142 "fish /home/olve"   : (qterminal.qterminal) 1280x769+0+0
0x480003    0  4786 "wrapper-2.0"       : (wrapper-2.0.Wrapper-2.0) 30x30-9999-9998
0x1c1405    0  4413 "fbxkb"             : (fbxkb.Fbxkb)        32x24+1055+773
0x1809e8    0  4373 "volumeicon"        : (volumeicon.Volumeicon) 24x24+1087+773
0x7000d3    0  4388 "keepassxc"         : (keepassxc.keepassxc) 24x24+1007+773
0x12c0091   0 14219 "YAD"               : (yad.Yad)            24x24+863+773
0x630eec    0  4389 "zim"               : (zim-desktop-wiki.zim-desktop-wiki) 24x24+935+773
0x4340bf    0 14504 "geany"             : (geany.Geany)        24x24+887+773
0x548832    0  4376 "clipit"            : (clipit.clipit)      24x24+1031+773
0x456a42    0  4381 "Sunflower"         : (Sunflower.__main__.py) 24x24+959+773
0xc4ab5e    0 21050 "qBittorrent"       : (qbittorrent.qBittorrent) 24x24+911+773
0x68001a    0  4379 "lxqt-powermanagement": (lxqt-powermanagement.lxqt-powermanagement) 24x24+983+773
0x6c157a    0  4378 "lxqt-notificationd": (lxqt-notificationd.lxqt-notificationd) 24x24+839+773
0x7000dc    0  4388 "keepassxc"         : (keepassxc.keepassxc) 190x50+1018+719
0x7000e3    0  4388 "keepassxc"         : (keepassxc.keepassxc) 182x75+268+22
0xc4ac22    0 21050 "[D: 468.3 KiB/s, U: 201.4 KiB/s] qBittorrent v4.": (qbittorrent.qBittorrent) 1280x769-3-3
0x7000b2    0  4388 "KPssXC [locked] - KeePassXC": (keepassxc.keepassxc) 1280x750+0+0
```

**Comment by gijsbers** [comment] 2021-05-27 15:35
How can Sunflower, lxqt-powermanagement and YAD become part of the system tray?

**Comment by gijsbers** [comment] 2021-05-27 19:12
The fbxkb problem has been explained here:
https://www.antixforum.com/forums/topic/change-fbxkb-icon-background/
In addition, you could try https://github.com/zen-tools/gxkb
and the icewm preference option `KeyboardLayouts`.

**Comment by gijsbers** [comment] 2021-05-29 22:26
I now have this set of system tray icons on AntiX 19.4:
![188-b](https://user-images.githubusercontent.com/4169687/120085935-b19b1180-c0dc-11eb-9d05-29c427716ff3.png)
Sunflower simply refuses to update its system tray icon.
Can't do anything about that, but you could report it to Sunflower.

The only way I could reliably reproduce the background artefacts
you reported in your screenshot, is when I start the system tray
applications and then toggle the setting for `Alpha`.

AntiX 19.4 icewm has some problems:

- its /etc/skel/.icewm/preferences is outdated.
- icehelp can't locate a `file` icon.
- icehelp can't find the IceWM manual.
- the icewm shutdown command has no effect.

**Comment by cheapy** [comment] 2021-06-24 01:01
I'll help with the antiX setup.

**Comment by cheapy** [comment] 2021-06-24 01:44
icehelp - Actually it can find the manual if you run one of the other options like FAQ first.  I've never seen icehelp before, so need to find out where it gets it's configuration.  It seems to run differently when run from the menu.  The manual is coming from /usr/share/doc/icewm-common/html/icewm.html when I run it from the menu or icehelp, not from the web.  There were a couple times it ran from the web, though.   Maybe that is causing it.

I added it to my toolbar and it worked.  The file icon isn't pretty but there.
prog "IceWM Help" file.png icehelp

This testing was done on my main system which runs all the antiX19.4 code, but my customized IceWM settings.  I will boot up a stock antiX19.4 full and try it there...

I will also get a fresh preferences default and merge it for the devs.
Not sure on shutdown.  On antiX that might be a bit unusual given all the persistence options etc.  Maybe it's just a question of getting the right command into the preferences file.

**Comment by gijsbers** [comment] 2021-06-24 05:33
@cheapy Good!

Of course the simplistic file icon can always be replaced with something much prettier. It just needed to find one, which is included in the icewm distribution.

The problem with the current shutdown menu entry is that it suggests it will shut down, but then doesn't do anything. Then it is better to define it as empty. Then it won't be shown in the menu.

Is there also hope for a recent roxterm version 3.11.1?

**Comment by cheapy** [comment] 2021-06-24 05:53
The antiX devs are very responsive with anything related to Rox and IceWM given they are the antiX primary defaults.  I will test with a stock setup tomorrow I hope, and see what I can resolve (hopefully preferences, shutdown and icon) before passing it on.  I will also pass on the links to here so there is no miscommunication.  I've been doing that with the previous improvements you have provided and suggested, and it has worked pretty well.

PS: given Bullseye status, I will also check my Bullseye setup and make sure all will be well there.
I see you meant RoxTerm.  I'll ask.  I don't see any Debian based 3.11 verions in repology.   I will ask for you.

**Comment by cheapy** [comment] 2021-06-25 06:20
I'm working from a fresh, fully up to date antiX 19.4.1 full USB machine tonight.

antiX doesn't include genpref.  Maybe over the weekend I'll clone it and get that.  The /etc/skel preferences file is coming from a different package, but I can probably merge them well.

I'm sorry on the file icon.  That is the antiX Blueday default file icon, based on using a papirus icon set, so its displaying correctly, from a program standpoint.  The system also comes with a set of numix-square icons by default that the user can switch to.

On the shutdown issue I can see that the antiX exit menu works differently depending on whether installed or live, and so your suggestion to not shutdown from from icewm seems correct to me.  It looks like it needs to be removed from preferences.

On icehelp, it runs fine from a terminal, but it's not on the menu.  When I ran it from the terminal it did have the file icon you disliked in the top right, and it opens a file as a web page with the help version from the /usr/share/doc/icewm-common/html/icewm.html file by default, which looks correct, although it has version 2.4.0 of icewm and the help says 2.2.1, but its recent from Mar 17th 2021.  We do have a separate Help menu with an IceWM submenu.  We have the FAQ and Manual available there, opening from the local drive with Dillo by default, as well as an older article/review of IceWM.  It's good to have the basics on the local drive in case the person doesn't have internet access, and I see you thought of that with your DOCDIR setting.   Maybe we could run icehelp from our menu instead of the manual?  

If you are having some other issue running icehelp, let me know so I can try to duplicate it or get it setup differently if you have a better way, and the Devs are ok with changing it.  I will forward this text to them.

**Comment by cheapy** [comment] 2021-06-26 19:45
Would 3.10.1 of RoxTerm help?    This was posted by stevo from MX Linux

https://drive.google.com/file/d/1Eq-bdEJJ2FsX9Bn6xCR209LS9sXyVigi/view

**Comment by gijsbers** [comment] 2021-06-26 19:53
3.10.1 is from one year ago. 3.11.1 is from six weeks ago. You can find it here:
https://launchpad.net/~h-realh/+archive/ubuntu/roxterm/+packages
Click on "roxterm - 3.11.1-1ppa1focal1". Is there a problem?

**Comment by cheapy** [comment] 2021-06-26 19:57
I'm not a super techie.  I'm more of a "user interface" guy

I'll ask stevo if he can package the newest one :)  

Once a package gets to the MX repos, I have usually been able to get it to install and run on antiX as well.

**Comment by cheapy** [comment] 2021-06-26 20:08
I'll test it and post again if 3.11.1 gets to the repos

**Comment by cheapy** [comment] 2021-06-29 12:33
ROXTerm 3.11.1 is now available in the MX testing repo

deb http://mxrepo.com/mx/testrepo/ buster test

I was able to install and run it on antiX 19.4 Full

**Comment by cheapy** [comment] 2021-07-01 04:36
A point to note, I was told Roxterm 3.x uses 10 mb more memory than Roxterm 2.95, and given that many antiX users have very low resource machines, with Roxterm being antiX's default terminal, the 2.95 was chosen as the installed version.  I didn't notice any difference myself as far as functionality, but happy to help get the 3.11.1 available for people wanting or needing a GTK3 version.

**Closed as completed** 2023-02-13 10:21 UTC
Labels: bug
