### ISSUE TITLE
Bugs in icewm-menu-fdo

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/icewm#263] opened 2018-04-27 19:54 UTC
1) desktop-files in ~ /.local/share/applications not override files in /usr/share/applications, but add new menu items.

2) The application is added only to one submenu (first alphabetically?), but not all registered in "Categories".

3) In the presence of the incorrect link on the desktop-file, the menu forms not completely.

4) Submenu have no own icons (the icon of "folder" is used).

Example:
libreoffice5.4-math.desktop
Categories=Office; Spreadsheet; Education;...

to 2) In icewm-menu-fdo the application is present only at the Education submenu (in icewm-xdg-menu/xde-menugen - in the Education and Office submenu)

to 1) Copy libreoffice5.4-math.desktop in ~ /.local/share/applications, delete "Office" and "Education", write "Graphics". In fdo - the application in the "Education" and "Graphics" submenu (in xdg/xde - only in the Graphics submenu). 

to 3) My libreoffice5.4-math.desktop is the link on the file in folder /opt.
If to edit the link so that he pointed to not existing file, then the half of the menu disappears.

**Comment by bbidulock** [comment] 2018-04-27 20:03
You might consider using [xde-menu](https://github.com/bbidulock/xde-menu), which is fully XDG compliant and does a better job of populating the icewm applications menu.

**Comment by arsonoff** [comment] 2018-04-27 20:13
Can include this utility in structure of icewm, instead of icewm-menu-fdo?

**Comment by bbidulock** [comment] 2018-05-11 01:32
No, because it is meant to work with other window managers too.

**Comment by frankzen** [comment] 2018-06-17 20:06
Maybe because of my age, or the phase of the moon but I dl'ed the zip file, added the dependencies which configure wanted, compiled and installed. But for the life of me I cannot come up with a command  line to generate a menu for icewm. It's configure files reside in ~/.icewm. Can you help? I certainly hope so.

**Comment by bbidulock** [comment] 2018-06-18 07:11
I think that would be `icewm-menu-fdo` as in the title of this issue...

**Comment by frankzen** [comment] 2018-06-18 11:26
You misunderstood. But considering what I posted, I am not surprised. I was talking about xde-menu. I should have made that clear.

**Comment by bbidulock** [comment] 2018-06-18 16:06
I use something like

    xde-menugen --wmname icewm --launch -o ~/.icewm/menu

**Comment by frankzen** [comment] 2018-06-18 20:28
Something still wrong for me.

frank@franklin:~$ xde-menugen --wmname icewm --launch -o ~/.icewm/menu
xde-menu: E:   xde-menu.c: +11009 : main() : excess non-option arguments near '/home/frank/.icewm/menu'
Usage:
    xde-menu [options]
    xde-menu {-m|--monitor} [options]
    xde-menu {-R|--replace} [options]
    xde-menu {-q|--quit} [options]
    xde-menu {-h|--help} [options]
    xde-menu {-V|--version}
    xde-menu {-C|--copying}

**Comment by bbidulock** [comment] 2018-06-19 01:58
Some brilliant fellow that think they know better broke optional argument options processing in getopt() in glibc..  ...again.  I happens about every 2 years.  Specify all option arguments fully with

    xdg-menugen --wmname=icewm --launch --output=~/.icewm/menu

and it will work until the bug reports are in again.

**Comment by bbidulock** [comment] 2018-06-19 04:06
I suppose this would work too:

    xde-menu -wmname icewm -launch -o"~/.icewm/menu"

**Comment by frankzen** [comment] 2018-06-19 11:39
No luck.

frank@franklin:~$ xde-menu -wmname icewm -launch -o"~/.icewm/menu"

** (xde-menu:1958): CRITICAL **: 07:36:31.620: gmenu_tree_new_for_path: assertion 'menu_path != NULL' failed
xde-menu: E:   xde-menu.c: +3849 : get_menu() : could not look up menu (null)
xde-menu: E:   xde-menu.c: +3968 : menu_generate() : could not allocat menu tree
frank@franklin:~$

**Comment by bbidulock** [comment] 2018-06-19 19:54
Sorry, that should have been:

    xde-menugen -wmname icewm -launch -o"~/.icewm/menu"

Neverttheless, you do need an XDG applications menu definition installed on your system.  Typically in `/etc/xdg/menus/${XDG_MENU_PREFIX}applications.menu`. `xde-menu` uses `$XDG_MENU_PREFIX:$XDG_VENDOR_ID-:arch-:xde-` to search for the applications menu.  The last two because Arch Linux has an arch-applications.menu installed, and `xde-` because the `xde-helpers` package places one in `/etc/xdg/xde/menus/xde-applications.menu`.  If you want to use the `xde-helpers` version, set the following:

    XDG_CONFIG_DIRS=/etc/xdg/xde:/etc/xdg
    XDG_DATA_DIRS=/usr/local/share:/usr/share/xde:/usr/share
    XDG_VENDOR_ID=xde
    XDG_MENU_PREFIX=xde-

Or, you can specify the exact file using the `--rootmenu` option, for example:

    xde-menugen -wmname icewm -rootmenu /etc/xdg/menus/lxde-applications.menu -launch -o"~/.icewm/menu"

**Comment by frankzen** [comment] 2018-06-21 13:25
On 06/19/2018 03:54 PM, Brian Bidulock wrote:
>
> Sorry, that should have been:
>
> |xde-menugen -wmname icewm -launch -o"~/.icewm/menu"|

No luck
frank@franklin:~/xde-menu-master$ xde-menugen -wmname icewm -launch 
-o"~/.icewm/menu"

** (xde-menu:19604): CRITICAL **: 09:10:05.378: gmenu_tree_new_for_path: 
assertion 'menu_path != NULL' failed
xde-menu: E:   xde-menu.c: +3849 : get_menu() : could not look up menu 
(null)
xde-menu: E:   xde-menu.c: +3968 : menu_generate() : could not allocat 
menu tree
frank@franklin:~/xde-menu-master$


> ||
>
> Neverttheless, you do need an XDG applications menu definition 
> installed on your system. Typically in 
> |/etc/xdg/menus/${XDG_MENU_PREFIX}applications.menu|. |xde-menu| uses 
> |$XDG_MENU_PREFIX:$XDG_VENDOR_ID-:arch-:xde-| to search for the 
> applications menu. The last two because Arch Linux has an 
> arch-applications.menu installed, and |xde-| because the |xde-helpers| 
> package places one in |/etc/xdg/xde/menus/xde-applications.menu|. If 
> you want to use the |xde-helpers| version, set the following:
>
> |XDG_CONFIG_DIRS=/etc/xdg/xde:/etc/xdg 
> XDG_DATA_DIRS=/usr/local/share:/usr/share/xde:/usr/share 
> XDG_VENDOR_ID=xde XDG_MENU_PREFIX=xde-|
    Put those into ~/.bash.rc no luck


> ||
>
> Or, you can specify the exact file using the |--rootmenu| option, for 
> example:
>
> |xde-menugen -wmname icewm -rootmenu 
> /etc/xdg/menus/lxde-applications.menu -launch -o"~/.icewm/menu" |
>

frank@franklin:~/xde-menu-master$ xde-menugen -wmname icewm -rootmenu 
/etc/xdg/menus/lxde-applications.menu -launch -o"~/.icewm/menu"
xde-menu: E:   xde-menu.c: +11009 : main() : excess non-option arguments 
near '/etc/xdg/menus/lxde-applications.menu'
Usage:
     xde-menu [options]
     xde-menu {-m|--monitor} [options]
     xde-menu {-R|--replace} [options]
     xde-menu {-q|--quit} [options]
     xde-menu {-h|--help} [options]
     xde-menu {-V|--version}
     xde-menu {-C|--copying}
frank@franklin:~/xde-menu-master$

Thanks for your help Brian but I think I'll stick with the menu maker 
I've been using.

**Comment by bbidulock** [comment] 2018-07-01 10:08
Is the issue closed, then?

**Comment by frankzen** [comment] 2018-07-01 15:44
Yes as far as I am concerned you can close it.

**Comment by arsonoff** [comment] 2018-07-01 21:28
I so understand icewm-menu-fdo there is no opportunity to correct?
It would be desirable to have the working utility in structure icewm.

Whether it is possible to compile xde-menu with built-in the module?
xde-menu (`xde-menugen -w icewm -t gnome -0`) cannot find the way to libreoffice icons (in /usr/share/icons/gnome/16x16/apps/).

**Comment by Code7R** [comment] 2018-08-10 15:57
Well, no matter what you decide, there are way too many hardcoded assumptions inside of icewm-menu-fdo. 

I am halfway through with refactoring it. Your input is very appreciated.

**Comment by Code7R** [comment] 2018-08-12 09:28
![embed_xdg_menu](https://user-images.githubusercontent.com/10660264/44000496-ef2b80b6-9e20-11e8-98f9-b318c0fb0fa0.png)

So, how do you like it?
That's embedded into main menu, I changed the entry for "Desktop Apps" to
`includeprog /usr/bin/icewm-menu-fdo --sep-before --no-sep-others`.

It includes icons now [1], translated menu names from descriptions, adds entries into all matching category menues [2], and looks for multiple folders in $XDG_DATA_HOME [3]. And should be a bit faster now.

(1) the icon name resolution is still not fully standard conform - on themed descriptions, icewm does not yet probe for more general names, i.e. try both applications-education-science.png and applications-education.png . It may should also thread app and category icons separately. I would like to see the opinion from @bbidulock or @gijsbers prior to start implementing a strategy here.

(2) Subcategories defined in XDG spec are not supported yet. WIP, when I find more time.

(3) I hope that fixes the original first issue from the bug report because otherwise I don't know how to reproduce it. The overriding or same apps entries has been available from the start, however, it uses the Name field as key. So if that differs, it won't match and appear twice. Any better idea how to detect same app?

@bbidulock Can we make this thing (see screenshot) become default configuration? I also added some option to the tool to avoid insertion of pointless section separator in case no XDG data is found.

PS: the example also sneaks icons from other XDG themes via `IconPath="/usr/share/icons/hicolor:/usr/share/icons:/usr/share/pixmaps:/usr/share/icons/oxygen/base:/usr/share/icons/gnome:/usr/share/icons/Adwaita:/usr/share/icons/Tango"`

**Comment by bbidulock** [comment] 2018-08-12 18:32
@Code7R : Yes, please make it the default configuration.

**Comment by Code7R** [comment] 2018-08-19 15:55
So, added everything. Implemented the submenu spec as far as I understood it.

I think to remove a few details, though. The GTK, Qt and ConsoleOnly submenues look creepy, hardly anybody can make much use of this subcategories.

**Comment by Code7R** [comment] 2018-09-08 09:29
@arsonoff Please confirm that the current version (in icewm-1-4-BRANCH) meets your expectations and if not, what is still missing.

(In case you are using Debian packages, the current version in sid/testing is similar to the git version except for l10n quality)

**Comment by arsonoff** [comment] 2018-09-09 12:32
icewm-menu-fdo:
[![2018-09-09-143315_1920x1200_scrot.png](https://s8.postimg.cc/8ig0nygv9/2018-09-09-143315_1920x1200_scrot.png)](https://postimg.cc/image/v757niy8x/)

icewm-xdg-menu (or xde-menugen):
[![2018-09-09-143328_1920x1200_scrot.png](https://s8.postimg.cc/5pmt3ht91/2018-09-09-143328_1920x1200_scrot.png)](https://postimg.cc/image/62e79obip/)

It is too much groups of the menu (Audio, AudioVideo, Video ?!), too much  submenu.
I do not know as it is necessary according to the standard, but icewm-xdg-menu and xde-menugen generate almost identical menus (less groups, less submenu).

**Comment by Code7R** [comment] 2018-09-19 17:11
@arsonoff On your screenshot, I see just NO submenus for -xdg generator, not just LESS submenu. This is, of course, much easier to handle, implementation-wise.

Anyhow, I added an option to skip generation of submenus whatsoever: --no-sub-cats . Is this what you want?

**Comment by arsonoff** [comment] 2018-09-21 00:58
I have (in xdg and xde) enclosed submenu (one :) ).
But I have no submenu "Education" as I am override "libreoffice6.0-math.desktop" 
in "~/.local/share/applications".
[![2018-09-20-131044_1600x1200_scrot.png](https://i.postimg.cc/VsDHsHKb/2018-09-20-131044_1600x1200_scrot.png)](https://postimg.cc/hhQ0pMWS)
In fdo it looks so:
[![2018-09-20-131101_1600x1200_scrot.png](https://i.postimg.cc/LXvvXn3M/2018-09-20-131101_1600x1200_scrot.png)](https://postimg.cc/jwwy3q18)

It is not easier to borrow the code of generation of the menu from xde-menu (completely working decision), than to think out from scratch?

**Comment by Code7R** [comment] 2018-10-03 18:22
Hm, which parts exactly are you complaining about?

a) The missing icons? That's because you probably have not recompiled icewm or do not have all themes in the icon path. Maybe xde-menu goes extra rounds and generates STATIC paths for the icons... but I would not go that way. Instead, I have modded the icon lookup code (in icewm itself!) to get folder icons from the XDG assets folders. See my screenshot above.

b) or the lack of Electronics menu? Sorry, that is a bug in xde-menu!
Just read the spec: https://specifications.freedesktop.org/menu-spec/menu-spec-latest.html#additional-category-registry
Relevant part: "If the Related Categories column is blank, the Additional Category can be used with any Main Category."
It does NOT say "become a Main Category", which is apparently what xde-menu does.

And what is the problem with Education menu? You added the keyword (as said above) so you got the menu. Is the entry not in the that menu now or what?
If something is NOT ok that please elaborate on what exactly you expect and only then how the result differs.

**Comment by arsonoff** [comment] 2018-10-05 17:08
> a) The missing icons? That's because you probably have not recompiled icewm or do not have all themes in the icon path. 

Yes, icons can be received having added paths to IconPath. 
Can be necessary to add to the configuration by default at least `IconPath="~/.local/share/icons:/usr/share/icons/Adwaita:...`, but icewm does not understand value `~` and `$HOME` :(


> b) or the lack of Electronics menu? Sorry, that is a bug in xde-menu!

I have the installed package [electronics-menu](http://rpmfind.net/linux/rpm2html/search.php?query=electronics-menu&submit=Search+...)  and same "bug" in icewm-xdg-menu/xde-menugen/openbox.


> And what is the problem with Education menu?

I shall not have it (and it is not in icewm-xdg-menu/xde-menugen/openbox) as I created the file ~/.local/share/applications/libreoffice6.0-math.desktop (see paragraph 1 of issue):
```
cp /usr/share/applications/libreoffice6.0-math.desktop ~/.local/share/applications/
sed -i 's/Education\;Science\;//' ~/.local/share/applications/libreoffice6.0-math.desktop
```
And it is the only program which I had in the menu Education.

> Audio, AudioVideo, Video

:(

**Closed as completed** 2024-04-16 19:27 UTC
Labels: bug, verification-pending
